### ISSUE TITLE
Porting weights

### ISSUE THREAD

**Issue by relh** [titu1994/Keras-DualPathNetworks#5]
The pre-trained weights are available in MXNet and Pytorch:

https://github.com/cypw/DPNs
https://github.com/rwightman/pytorch-dpn-pretrained

There are converters that convert between Pytorch and Keras:
https://github.com/ysh329/deep-learning-model-convertor
https://github.com/gzuidhof/nn-transfer
https://github.com/nerox8664/pytorch2keras

I'm guessing the issue with porting the weights is the introduction of the lambda layer for the DPN. Is that correct?

Let me know if you think this is a doable task and if you had any recommendations for where to start if I was to approach this.

**Comment by titu1994** [comment]
I'd suggest waiting for Tensorflow 1.6. The reason is that there is recent support for Grouped Convolutions in the latest cuDNN, which will inevitably get incorporated into Tensorflow, and likewise into Keras at some stage. 

The Lamba hack is just that, a hack. Also, I can't guarantee that the bn-conv-relu is correct. I suggest using the PyTorch version if necessary. 

In all likelihood, I won't work on this anymore. NASNet surpasses it's performance, making it less of a priority.
